import pyotp
import base64
import time

# Set up the key for generating HOTP codes
key = "TwoFactorAuthenticator"
base32_key = base64.b32encode(key.encode())

# Create an instance of HOTP with the key
hotp = pyotp.HOTP(base32_key)

# Generate and print the first six HOTP codes
for i in range(6):
    print(hotp.at(i))

# Verify the next five HOTP codes generated by the user
counter = 0
for i in range(5):
    start_time = time.time() # get the start time of the verification process
    input_code = input("Enter the 2AF Code: ")
    end_time = time.time() # get the end time of the verification process
    
    # Verify the code only if it was entered within 30 seconds
    if end_time - start_time <= 30:
        if hotp.verify(input_code, counter):
            print("Code verified!")
            counter += 1
        else:
            print("Invalid code. Please try again.")
    else:
        print("Code verification timed out. Please try again.")
